### ISSUE TITLE
Security bug

### ISSUE THREAD

**Issue by andrewdavey** [VisualReCode/Cocoon#26]
I think I've found a nasty security-related bug. What's the best way to disclose this without publicly posting it?

**Comment by markrendle** [comment]
You can email me mark@rendlelabs.com

**Comment by conficient** [comment]
Suspect we had the same issue which I was discussing with Mark. The latest release on Nuget, version 1.0.21-rc1 should fix this. It's running in my environment and the bug does appear to be fixed.

**Comment by andrewdavey** [comment]
The latest version is working for me too. Thanks for the speedy response on this.
