### ISSUE TITLE
Long HTTP requests causes YARP to Timeout

### ISSUE THREAD

**Issue by lorenzodimauro97** [VisualReCode/Cocoon#28]
Hello!

I am currently testing this library to allow an incremental migration of a BIG Webforms application (>160 pages) to Blazor server.

First tests seem to run apparently fine however some pages take a very good while to load in the web forms app (we're talking about 2-5 minutes just to load) which causes YARP to fail miserably.

Here is a Pastebin for all intents and purposes: https://pastebin.com/cHHkbv9m

Now the question is, how should I go about appropriately handling the timeout value using this Library?

**Comment by khellang** [comment]
You could try setting the `Cocoon:Proxy:Timeout` configuration value?

https://github.com/VisualReCode/Cocoon/blob/b616544200d14e0e55f9e1fd4a9dd84074c99f71/main/src/ReCode.Cocoon.Proxy/Proxy/CocoonProxy.cs#L60-L63

**Comment by lorenzodimauro97** [comment]
Thanks! I was dumb enough to not be able to find that part of code when I searched, but I hope this'll help others who also were not able to find anything about it!
